[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
my_oapp = "67K1bWanFMMgCT2Yx6MhKZNk8ng6DiRCNVPNjqWe2WPL"

[programs.localnet]
my_oapp = "AApBCUDXvRkTJ2kajN9xpLdT2MUTE6bDD883vPn6VU9R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/chorster/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 10000000 sdk/tests/**/*.test.ts"
