[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_oapp = "9hYxCB1KnVzRpCBtKktvCA77F28pE8H35g4WgiopzwyJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/chorster/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 10000000 sdk/tests/**/*.test.ts"
